### PR TITLE
Rework "config" attributes

### PR DESCRIPTION
**Pull request by jmccann**
For drone config items that drive Drone behavior through either ENV in the container or `dronerc` for package installs move attributes parent from `default['drone']` to `default['drone']['config']`.

This would be a BREAKING change so version bump in future would need to be MAJOR.  But I think this helps to simplify managing the config quite a bit.

### CODE REVIEW

**Comment by jmccann** [comment]
@justincampbell Have time to review this? 😄

**Comment by jmccann** [comment]
@justincampbell Do you have any thoughts on this?

**Comment by justincampbell** [comment]
@jmccann Looks good to me. I'm not currently using Chef for anything, so I don't really have the context anymore to properly review these. Not sure if any other collaborators on the repo would like to review.

**Comment by justincampbell** [comment]
Would also happily transfer ownership of this to you or the @drone org /cc @bradrydzewski

**Comment by jmccann** [comment]
@justincampbell Wouldn't mind taking ownership if @drone / @bradrydzewski passes on it.  So we will see what they say.  Thanks!

**Comment by bradrydzewski** [comment]
@justincampbell perhaps transfer ownership to @jmccann for now, and we can look into making this an official drone project in the future? thanks :smile:

**Comment by jmccann** [comment]
@justincampbell If you transfer ownership to me could you be sure to add me as a collaborator or transfer https://supermarket.chef.io/cookbooks/drone for me as well so I can continue to publish updates to supermarket?  I'm "jmccann" there (https://supermarket.chef.io/users/jmccann).  Thanks!

**Comment by predominant** [comment]
:+1:

**Pull request merged**
