### PR TITLE
Bump chef_nginx, chef-vault and ssl_certificate to the latest versions

### PR DESCRIPTION
**Pull request by szymonpk**
Recently we've started to use your cookbook, unfortunately old nginx and chef-vault caused us some issues. I hope you don't mind I've cleaned cookbook a little bit.

Sorry I've touched version in metadata, but it was interfering with cookbook version from supermarket.

In addition:
- Remove ubuntu 15.10 from supported platforms list, it isn't supported
any longer.
- Use Berksfile source within chef.io domain (one http redirect less).
- Group test/development cookbooks in Berksfile.
- Add guards for params passed to docker_* resouces (It caused
unecessary warnings during rspec/chef run).
- Extract _nginx spec from reverse_proxy_spec.
- Use native nginx_site instead of injecting params into chef_nginx
default template.

### CODE REVIEW

**Comment by jmccann** [comment]
@szymonpk Thanks for the PR.  Unfortunately I'm going to pass because

* There are now lots of conflicts
* I plan on removing reverse proxy support
* Some of the updates have been made already

- Jake

**Comment by szymonpk** [comment]
Sure, no worries. If I may ask. When do you want to remove nginx? Outdated cookboks are major blocker for us :(

**Comment by jmccann** [comment]
I started work on this yesterday @ https://github.com/jmccann/chef-drone/tree/remove_old

Hope to be done tomorrow or Monday.

**Comment by jmccann** [comment]
@szymonpk Just cut release `4.0.0`.

**Pull request closed without merging**
